// SPDX-FileCopyrightText: 2026 quendoris
// SPDX-License-Identifier: AGPL-3.0-only

#include "aeris/storage/resource.hpp"
#include "aeris/util/sha256.hpp"

#include <chrono>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <memory>
#include <string>
#include <vector>

namespace {

int failures = 0;

void expect(const char* name, const bool condition) {
    if (condition) return;
    ++failures;
    std::cerr << "FAIL " << name << '\n';
}

class Fixture final {
public:
    Fixture() {
        const auto stamp = std::chrono::high_resolution_clock::now()
                               .time_since_epoch()
                               .count();
        root_ = std::filesystem::temp_directory_path() /
            ("aeris-resource-bytes-test-" + std::to_string(stamp));
        std::filesystem::create_directories(root_);

        aeris::storage::ProjectCreateOptions options{};
        options.timestamp_utc = "2026-09-05T14:30:00Z";
        options.project_uuid = "72b07557-27cb-49a8-a235-c3a0b5a19d87";
        auto created = aeris::storage::ProjectStore::create(root_ / "world.aeris", options);
        if (created.ok()) project_ = std::move(created.store);
    }

    ~Fixture() {
        project_.reset();
        std::error_code ignored;
        (void)std::filesystem::remove_all(root_, ignored);
    }

    [[nodiscard]] aeris::storage::ProjectStore* project() noexcept {
        return project_.get();
    }

    [[nodiscard]] std::filesystem::path project_path() const {
        return root_ / "world.aeris";
    }

    void close() noexcept { project_.reset(); }

private:
    std::filesystem::path root_;
    std::unique_ptr<aeris::storage::ProjectStore> project_;
};

}  // namespace

int main() {
    using namespace aeris::storage;

    Fixture fixture{};
    ProjectStore* project = fixture.project();
    expect("project creates", project != nullptr);
    if (project == nullptr) return EXIT_FAILURE;

    std::vector<std::uint8_t> bytes(kEmbeddedResourceChunkBytes + 137U);
    for (std::size_t index = 0U; index < bytes.size(); ++index) {
        bytes[index] = static_cast<std::uint8_t>((index * 29U + 11U) & 0xffU);
    }

    ProjectResourceIdentity identity{};
    identity.resource_id = "generated.elevation.tile.test";
    identity.sha256 = aeris::util::sha256_bytes(bytes.data(), bytes.size()).hex();
    identity.media_type = "application/vnd.aeris.elevation-tile.v1";
    identity.size_bytes = static_cast<std::uint64_t>(bytes.size());
    identity.retrieval_uri = "urn:aeris:test:generated-elevation-tile";
    identity.required_for_reproduction = true;

    const auto embedded = embed_resource_bytes(
        *project,
        identity,
        bytes,
        "2026-09-05T14:30:01Z");
    expect("generated bytes embed", embedded.ok());
    expect("generated bytes insert", embedded.inserted);
    expect("generated bytes commit", embedded.durably_committed);
    expect("generated bytes advance one revision", project->metadata().revision == 1U);

    const auto listed = list_project_resources(*project);
    expect("generated resource lists", listed.ok() && listed.records.size() == 1U);
    if (listed.ok() && listed.records.size() == 1U) {
        expect("generated resource embedded",
               listed.records.front().storage_mode == ResourceStorageMode::embedded);
        expect("generated resource uses canonical two chunks",
               listed.records.front().chunk_count == 2U);
    }

    std::vector<std::uint8_t> streamed;
    const Status stream_status = stream_embedded_resource(
        *project,
        identity.resource_id,
        [&](const void* data, const std::size_t size) {
            const auto* first = static_cast<const std::uint8_t*>(data);
            streamed.insert(streamed.end(), first, first + size);
            return Status::success();
        });
    expect("generated bytes stream", stream_status.ok());
    expect("generated bytes round trip exactly", streamed == bytes);
    expect("generated bytes pass deep integrity", project->verify_integrity().ok());

    const auto retry = embed_resource_bytes(
        *project,
        identity,
        bytes,
        "2026-09-05T14:30:02Z");
    expect("generated bytes exact retry succeeds", retry.ok());
    expect("generated bytes exact retry idempotent", !retry.durably_committed);
    expect("generated bytes retry keeps revision", project->metadata().revision == 1U);

    ProjectResourceIdentity wrong_size = identity;
    wrong_size.resource_id = "generated.bad-size";
    wrong_size.size_bytes += 1U;
    const auto rejected_size = embed_resource_bytes(
        *project,
        wrong_size,
        bytes,
        "2026-09-05T14:30:03Z");
    expect("generated byte size mismatch rejected",
           rejected_size.status.error == StorageError::integrity_failed);
    expect("size rejection keeps revision", project->metadata().revision == 1U);

    ProjectResourceIdentity wrong_hash = identity;
    wrong_hash.resource_id = "generated.bad-hash";
    wrong_hash.sha256 = std::string(64U, '0');
    const auto rejected_hash = embed_resource_bytes(
        *project,
        wrong_hash,
        bytes,
        "2026-09-05T14:30:04Z");
    expect("generated byte hash mismatch rejected",
           rejected_hash.status.error == StorageError::integrity_failed);
    expect("hash rejection rolls back resource",
           list_project_resources(*project).records.size() == 1U);
    expect("hash rejection keeps revision", project->metadata().revision == 1U);

    const auto null_rejected = embed_resource_bytes(
        *project,
        identity,
        nullptr,
        1U,
        "2026-09-05T14:30:05Z");
    expect("non-empty null bytes rejected",
           null_rejected.status.error == StorageError::invalid_argument);

    const auto frozen = freeze_project(*project, "2026-09-05T14:30:06Z");
    expect("generated resource project freezes", frozen.ok());
    expect("freeze advances revision", project->metadata().revision == 2U);

    const std::filesystem::path path = fixture.project_path();
    fixture.close();
    project = nullptr;

    auto reopened = ProjectStore::open(path);
    expect("generated resource project reopens", reopened.ok());
    if (reopened.ok()) {
        expect("generated resource project remains frozen", reopened.store->metadata().frozen);
        expect("reopened generated resource passes integrity",
               reopened.store->verify_integrity().ok());
    }

    if (failures != 0) return EXIT_FAILURE;
    std::cout << "aeris_test_resource_bytes: PASS bytes=" << bytes.size() << '\n';
    return EXIT_SUCCESS;
}
